
#include <verilated.h>
#include <verilated_vcd_c.h>
#include "Vmailbox_controller.h"

static vluint64_t main_time = 0;
double sc_time_stamp() { return (double)main_time; }

static void tick(Vmailbox_controller* dut, VerilatedVcdC* tfp) {
    dut->clk = 0;
    dut->eval();
    if (tfp) tfp->dump(main_time);
    main_time++;

    dut->clk = 1;
    dut->eval();
    if (tfp) tfp->dump(main_time);
    main_time++;
}

static void reset(Vmailbox_controller* dut, VerilatedVcdC* tfp, int cycles=5) {
    dut->rst = 1;
    dut->bus_valid = 0;
    dut->bus_we = 0;
    dut->bus_addr = 0;
    dut->bus_wdata = 0;

    dut->txq_deq = 0;
    dut->rx_in_valid = 0;
    dut->rx_in_data = 0;
    dut->tx_done_valid = 0;
    dut->tx_done_slot = 0;

    dut->net_sp_we = 0;
    dut->net_sp_waddr = 0;
    dut->net_sp_wdata = 0;
    dut->net_sp_re = 0;
    dut->net_sp_raddr = 0;

    for (int i=0;i<cycles;i++) tick(dut, tfp);
    dut->rst = 0;
    tick(dut, tfp);
}

static uint32_t bus_read(Vmailbox_controller* dut, VerilatedVcdC* tfp, uint8_t addr) {
    dut->bus_valid = 1;
    dut->bus_we = 0;
    dut->bus_addr = addr;
    tick(dut, tfp);
    // read data is combinational under bus_valid; sample after tick
    uint32_t r = dut->bus_rdata;
    dut->bus_valid = 0;
    tick(dut, tfp);
    return r;
}

static void bus_write(Vmailbox_controller* dut, VerilatedVcdC* tfp, uint8_t addr, uint32_t data) {
    dut->bus_valid = 1;
    dut->bus_we = 1;
    dut->bus_addr = addr;
    dut->bus_wdata = data;
    tick(dut, tfp);
    dut->bus_valid = 0;
    dut->bus_we = 0;
    tick(dut, tfp);
}

static void expect(bool cond, const char* msg) {
    if (!cond) {
        VL_FATAL_MT(__FILE__, __LINE__, "", msg);
    }
}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);

    auto* dut = new Vmailbox_controller;

    auto* tfp = new VerilatedVcdC;
    dut->trace(tfp, 99);
    tfp->open("mailbox.vcd");

    reset(dut, tfp, 8);

    // Wait for init_done (STATUS bit2)
    for (int i=0;i<400;i++) {
        uint32_t st = bus_read(dut, tfp, 0x00);
        if (st & (1u<<2)) break;
        if (i==399) expect(false, "Timeout waiting for init_done");
    }

    // Scratchpad write/read (core side via regs)
    // write: addr=0x02, data=0xdeadbeef
    bus_write(dut, tfp, 0x18, 0x02);
    bus_write(dut, tfp, 0x1C, 0xdeadbeef);
    bus_write(dut, tfp, 0x20, 0x1);

    // read back
    bus_write(dut, tfp, 0x24, 0x02);
    bus_write(dut, tfp, 0x28, 0x1);
    // wait for rvalid
    for (int i=0;i<10;i++) {
        uint32_t rv = bus_read(dut, tfp, 0x30);
        if (rv & 1) break;
        if (i==9) expect(false, "Scratchpad read did not become valid");
    }
    uint32_t rd = bus_read(dut, tfp, 0x2C);
    expect(rd == 0xdeadbeef, "Scratchpad readback mismatch");

    // Program TX descriptor regs
    bus_write(dut, tfp, 0x04, 0x3);  // dest=3
    bus_write(dut, tfp, 0x08, 0x5);  // len=5

    // Send command
    bus_write(dut, tfp, 0x0C, 0x1);

    // Wait a couple cycles for alloc/enq
    for (int i=0;i<10;i++) tick(dut, tfp);

    uint32_t slot = bus_read(dut, tfp, 0x0C) & 0xFF;

    // Drain tx_queue (simulate transmit unit)
    // tx_queue's deq_valid is a 1-cycle pulse generated by the FIFO when a dequeue occurs.
    // visible immediately after the deq tick, or on next tick.
    while (!dut->txq_deq_ready) tick(dut, tfp);

    dut->txq_deq = 1;
    tick(dut, tfp);          // perform dequeue on this cycle
    dut->txq_deq = 0;

    // Capture the dequeue result (valid may be visible on next tick)
    if (!dut->txq_deq_valid) {
        tick(dut, tfp);
    }
    expect(dut->txq_deq_valid, "Expected txq_deq_valid after deq");
    uint32_t txd = dut->txq_deq_data;
    uint32_t got_slot = txd & 0xFF;
    uint32_t got_len  = (txd >> 8) & 0xFF;
    uint32_t got_dest = (txd >> 16) & 0xF;
    expect(got_dest == 0x3, "TX desc dest mismatch");
    expect(got_len  == 0x5, "TX desc len mismatch");
    expect(got_slot == slot, "TX desc slot mismatch");

    // Mark TX done => decrements refcount => slot returned to freelist eventually
    dut->tx_done_valid = 1;
    dut->tx_done_slot  = slot;
    tick(dut, tfp);
    dut->tx_done_valid = 0;

    for (int i=0;i<10;i++) tick(dut, tfp);

    // Simulate a received message arriving from network: {len=7, slot=9}
    // (In a real system the receive unit would allocate slot and write scratchpad)
    while (!dut->rx_in_ready) tick(dut, tfp);
    dut->rx_in_valid = 1;
    dut->rx_in_data  = (7u << 8) | 9u;
    tick(dut, tfp);
    dut->rx_in_valid = 0;

    // Core pops RX descriptor
    bus_write(dut, tfp, 0x10, 0x1);
    for (int i=0;i<5;i++) tick(dut, tfp);
    uint32_t rxdesc = bus_read(dut, tfp, 0x10) & 0xFFFF;
    uint32_t rx_slot = rxdesc & 0xFF;
    uint32_t rx_len  = (rxdesc >> 8) & 0xFF;
    expect(rx_slot == 9, "RX desc slot mismatch");
    expect(rx_len  == 7, "RX desc len mismatch");

    // Core releases slot 9
    bus_write(dut, tfp, 0x14, 9);

    for (int i=0;i<20;i++) tick(dut, tfp);

    // Basic sanity: rx_has_msg should now be 0
    uint32_t st2 = bus_read(dut, tfp, 0x00);
    expect(((st2 >> 1) & 1u) == 0u, "Expected rx_has_msg=0 after pop");

    tfp->close();
    delete tfp;
    delete dut;

    VL_PRINTF("PASS. Generated mailbox.vcd \n");
    return 0;
}
